In [1]:
import numpy as np
import collections
import os

path = os.path.abspath(os.getcwd())

from prep.derivatives import Preprocess_derivatives

from src.supplementary import Define_Derivatives
from src.term import normalize_ts, Term
from src.trainer import Equation_Trainer

Задаём функцию, позволяющую оценивать значений слагаемых уравнения. Это исполнение использует тензоры значений токенов на сетке и через поэлементное умножение тензоры, получает значения слагаемого. Далее, тензор преобразуется в вектор для использования в качестве признака в регрессии. 

In [2]:
def derivative_evaluator(term, eval_params):
    assert 'token_matrices' in eval_params and 'max_power' in eval_params
    if type(term) == Term:
        term = term.gene
    token_matrices = eval_params['token_matrices']
    value = np.copy(token_matrices[0])
    for var_idx in np.arange(eval_params['max_power'], term.shape[0], eval_params['max_power']):
        power = (np.sum(term[var_idx : var_idx + eval_params['max_power']]))
        value *= eval_params['token_matrices'][int(var_idx / float(eval_params['max_power']))] ** int(power)
    value = normalize_ts(value)
    value = value.reshape(np.prod(value.shape))
    return value    

Проводим препроцессинг данных и вычисляем значения производных на сетке. Вычисления довольно трудоёмкие => распараллелены, но всё равно могут занять относительно много времени, особенно если считать на ПК. Результаты препроцессинга сохраняем в отдельный файл, чтобы использовать при повторных запусках основного алгоритма. Это экономит время! Для примера используется решение волнового уравнения с белым шумом.

In [4]:
output_file_name = path + '/Preprocessing/Derivatives.npy'
filename =  path + '/Preprocessing/wave_noised.npy' 
poolsize = 4

field = np.load(filename)
Preprocess_derivatives(field, output_file_name, mp_poolsize=poolsize)

Executing on grid with uniform nodes:


Process ForkPoolWorker-4:
KeyboardInterrupt
Process ForkPoolWorker-2:
Process ForkPoolWorker-3:
Process ForkPoolWorker-1:
Traceback (most recent call last):
Traceback (most recent call last):
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 108, in worker
    task = get()
  File "/usr/lib/python3.6/multiprocessing/p

KeyboardInterrupt: 

(0, 0, 0)
(0, 0, 1)
(0, 0, 2)
(0, 0, 3)
(0, 0, 4)
(0, 0, 5)
(0, 0, 6)
(0, 0, 7)
(0, 0, 8)
(0, 0, 9)
(0, 0, 10)
(0, 0, 11)
(0, 0, 12)
(0, 0, 13)
(0, 0, 14)
(0, 0, 15)
(0, 0, 16)
(0, 0, 17)
(0, 0, 18)
(0, 0, 19)
(0, 0, 20)
(0, 0, 21)
(0, 0, 22)
(6, 31, 57)
(6, 31, 58)
(0, 0, 23)
(0, 0, 24)
(6, 31, 59)
(0, 0, 25)
(6, 31, 60)
(0, 0, 26)
(0, 0, 27)
(6, 31, 61)
(6, 31, 62)
(0, 0, 28)
(6, 31, 63)
(0, 0, 29)
(6, 31, 64)
(6, 31, 65)
(0, 0, 30)
(0, 0, 31)
(0, 0, 32)
(0, 0, 34)
(6, 31, 66)
(0, 0, 33)
(0, 0, 35)
(6, 31, 79)
(6, 31, 67)
(0, 0, 36)
(0, 0, 37)
(6, 31, 68)
(6, 31, 69)
(0, 0, 38)
(6, 31, 70)
(0, 0, 39)
(6, 31, 71)
(0, 0, 40)
(6, 31, 72)
(0, 0, 41)
(6, 31, 73)
(0, 0, 42)
(0, 0, 43)
(6, 31, 74)
(0, 0, 44)
(0, 0, 45)
(6, 31, 75)
(6, 31, 76)
(0, 0, 46)
(6, 31, 77)
(0, 0, 47)
(6, 31, 78)
(0, 0, 48)
(12, 63, 13)
(0, 0, 49)
(12, 63, 14)
(0, 0, 50)
(12, 63, 15)
(0, 0, 51)
(6, 31, 80)
(0, 0, 52)
(0, 0, 53)
(12, 63, 16)
(6, 31, 81)
(12, 63, 17)
(0, 0, 54)
(0, 0, 55)
(6, 31, 82)
(12, 63, 18)
(6, 

(12, 64, 55)
(0, 2, 34)
(18, 96, 4)
(6, 33, 25)
(12, 64, 56)
(0, 2, 35)
(0, 2, 36)
(6, 33, 26)
(0, 2, 37)
(18, 96, 5)
(6, 33, 27)
(12, 64, 57)
(0, 2, 38)
(18, 96, 6)
(6, 33, 28)
(12, 64, 58)
(18, 96, 7)
(0, 2, 39)
(12, 64, 59)
(6, 33, 29)
(18, 96, 8)
(0, 2, 40)
(6, 33, 30)
(0, 2, 41)
(18, 96, 9)
(12, 64, 60)
(0, 2, 42)
(6, 33, 31)
(18, 96, 10)
(18, 96, 11)
(6, 33, 32)
(12, 64, 61)
(12, 64, 62)
(6, 33, 33)
(0, 2, 43)
(6, 33, 34)
(12, 64, 63)
(18, 96, 12)
(0, 2, 44)
(0, 2, 45)
(12, 64, 64)
(6, 33, 35)
(18, 96, 13)
(0, 2, 46)
(12, 64, 65)
(6, 33, 36)
(0, 2, 47)
(12, 64, 66)
(18, 96, 14)
(0, 2, 48)
(6, 33, 37)
(12, 64, 67)
(0, 2, 49)
(12, 64, 68)
(12, 64, 69)
(6, 33, 38)
(12, 64, 70)
(18, 96, 15)
(6, 33, 39)
(0, 2, 50)
(12, 64, 71)
(0, 2, 51)
(0, 2, 52)
(6, 33, 40)
(18, 96, 16)
(12, 64, 72)
(12, 64, 73)
(18, 96, 17)
(0, 2, 53)
(18, 96, 18)
(0, 2, 54)
(0, 2, 55)
(12, 64, 74)
(18, 96, 19)
(6, 33, 41)
(0, 2, 56)
(6, 33, 42)
(18, 96, 20)
(0, 2, 57)
(6, 33, 43)
(12, 64, 75)
(0, 2, 58)
(18, 96, 

(18, 97, 63)
(12, 66, 11)
(0, 4, 39)
(18, 97, 64)
(12, 66, 12)
(0, 4, 40)
(6, 34, 78)
(12, 66, 13)
(0, 4, 41)
(6, 34, 79)
(12, 66, 14)
(18, 97, 65)
(18, 97, 66)
(0, 4, 42)
(12, 66, 15)
(6, 34, 80)
(18, 97, 67)
(0, 4, 43)
(18, 97, 68)
(0, 4, 44)
(12, 66, 16)
(0, 4, 45)
(18, 97, 69)
(6, 34, 81)
(18, 97, 70)
(18, 97, 71)
(18, 97, 72)
(0, 4, 46)
(6, 34, 82)
(12, 66, 17)
(18, 97, 73)
(6, 34, 83)
(18, 97, 74)
(18, 97, 75)
(12, 66, 18)
(18, 97, 76)
(18, 97, 77)
(6, 34, 84)
(0, 4, 47)
(12, 66, 19)
(18, 97, 78)
(0, 4, 48)
(6, 34, 85)
(0, 4, 49)
(12, 66, 20)
(18, 97, 79)
(6, 34, 86)
(18, 97, 80)
(0, 4, 50)
(0, 4, 51)
(12, 66, 21)
(18, 97, 81)
(0, 4, 52)
(6, 34, 87)
(0, 4, 53)
(12, 66, 22)
(6, 34, 88)
(0, 4, 54)
(0, 4, 55)
(18, 97, 82)
(6, 34, 89)
(12, 66, 23)
(0, 4, 56)
(18, 97, 83)
(0, 4, 57)
(6, 34, 90)
(18, 97, 84)
(12, 66, 24)
(18, 97, 85)
(0, 4, 58)
(12, 66, 25)
(6, 34, 91)
(0, 4, 59)
(12, 66, 26)
(0, 4, 60)
(18, 97, 86)
(6, 34, 92)
(12, 66, 27)
(12, 66, 28)
(0, 4, 61)
(6, 34, 93)
(12, 66, 

(18, 99, 34)
(0, 6, 22)
(12, 67, 71)
(6, 36, 33)
(18, 99, 35)
(6, 36, 34)
(12, 67, 72)
(6, 36, 35)
(6, 36, 36)
(12, 67, 73)
(0, 6, 23)
(18, 99, 36)
(12, 67, 74)
(0, 6, 24)
(12, 67, 75)
(6, 36, 37)
(12, 67, 76)
(12, 67, 77)
(18, 99, 37)
(6, 36, 38)
(0, 6, 25)
(0, 6, 26)
(6, 36, 39)
(0, 6, 27)
(18, 99, 38)
(12, 67, 78)
(0, 6, 28)
(6, 36, 40)
(0, 6, 29)
(12, 67, 79)
(0, 6, 30)
(6, 36, 41)
(18, 99, 39)
(12, 67, 80)
(0, 6, 31)
(6, 36, 42)
(18, 99, 40)
(0, 6, 32)
(12, 67, 81)
(6, 36, 43)
(18, 99, 41)
(18, 99, 42)
(0, 6, 33)
(0, 6, 34)
(18, 99, 43)
(6, 36, 44)
(12, 67, 82)
(18, 99, 44)
(0, 6, 35)
(12, 67, 83)
(6, 36, 45)
(0, 6, 36)
(18, 99, 45)
(12, 67, 84)
(6, 36, 46)
(18, 99, 46)
(12, 67, 85)
(0, 6, 37)
(6, 36, 47)
(12, 67, 86)
(18, 99, 47)
(12, 67, 87)
(6, 36, 48)
(0, 6, 38)
(18, 99, 48)
(6, 36, 49)
(6, 36, 50)
(18, 99, 49)
(12, 67, 88)
(6, 36, 51)
(0, 6, 39)
(18, 99, 50)
(12, 67, 89)
(6, 36, 52)
(0, 6, 40)
(18, 99, 51)
(12, 67, 90)
(6, 36, 53)
(18, 99, 52)
(0, 6, 41)
(18, 99, 53)
(12, 67,

(0, 7, 85)
(0, 7, 86)
(6, 37, 92)
(12, 69, 31)
(19, 0, 12)
(19, 0, 13)
(0, 7, 87)
(6, 37, 93)
(0, 7, 88)
(19, 0, 14)
(12, 69, 32)
(0, 7, 89)
(19, 0, 15)
(19, 0, 16)
(6, 37, 94)
(12, 69, 33)
(0, 7, 90)
(19, 0, 17)
(6, 37, 95)
(19, 0, 18)
(12, 69, 34)
(0, 7, 91)
(19, 0, 19)
(12, 69, 35)
(6, 37, 96)
(0, 7, 92)
(19, 0, 20)
(6, 37, 97)
(12, 69, 36)
(19, 0, 21)
(0, 7, 93)
(0, 7, 94)
(19, 0, 22)
(12, 69, 37)
(19, 0, 23)
(19, 0, 24)
(6, 37, 98)
(0, 7, 95)
(12, 69, 38)
(19, 0, 25)
(6, 37, 99)
(0, 7, 96)
(19, 0, 26)
(12, 69, 39)
(0, 7, 97)
(6, 37, 100)
(12, 69, 40)
(12, 69, 41)
(0, 7, 98)
(19, 0, 27)
(12, 69, 42)
(0, 7, 99)
(6, 38, 0)
(12, 69, 43)
(19, 0, 28)
(6, 38, 1)
(19, 0, 29)
(0, 7, 100)
(6, 38, 2)
(12, 69, 44)
(0, 8, 0)
(12, 69, 45)
(6, 38, 3)
(19, 0, 30)
(0, 8, 1)
(6, 38, 4)
(12, 69, 46)
(0, 8, 2)
(6, 38, 5)
(19, 0, 31)
(0, 8, 3)
(12, 69, 47)
(12, 69, 48)
(19, 0, 32)
(6, 38, 6)
(0, 8, 4)
(6, 38, 7)
(19, 0, 33)
(12, 69, 49)
(19, 0, 34)
(6, 38, 8)
(12, 69, 50)
(19, 0, 35)
(6, 38, 9)
(0, 8,

(0, 9, 68)
(6, 39, 66)
(12, 70, 78)
(19, 1, 93)
(0, 9, 69)
(6, 39, 67)
(19, 1, 94)
(0, 9, 70)
(12, 70, 79)
(6, 39, 68)
(12, 70, 80)
(0, 9, 71)
(6, 39, 69)
(0, 9, 72)
(0, 9, 73)
(19, 1, 95)
(0, 9, 74)
(6, 39, 70)
(12, 70, 81)
(0, 9, 75)
(6, 39, 71)
(12, 70, 82)
(0, 9, 76)
(6, 39, 72)
(19, 1, 96)
(0, 9, 77)
(6, 39, 73)
(12, 70, 83)
(0, 9, 78)
(12, 70, 84)
(6, 39, 74)
(19, 1, 97)
(0, 9, 79)
(12, 70, 85)
(19, 1, 98)
(6, 39, 75)
(12, 70, 86)
(0, 9, 80)
(19, 1, 99)
(0, 9, 81)
(12, 70, 87)
(6, 39, 76)
(12, 70, 88)
(6, 39, 77)
(12, 70, 89)
(6, 39, 78)
(12, 70, 90)
(12, 70, 91)
(19, 1, 100)
(12, 70, 92)
(6, 39, 79)
(19, 2, 0)
(12, 70, 93)
(0, 9, 82)
(19, 2, 1)
(12, 70, 94)
(0, 9, 83)
(12, 70, 95)
(19, 2, 2)
(12, 70, 96)
(0, 9, 84)
(19, 2, 3)
(12, 70, 97)
(0, 9, 85)
(12, 70, 98)
(12, 70, 99)
(19, 2, 4)
(6, 39, 80)
(0, 9, 86)
(12, 70, 100)
(19, 2, 5)
(0, 9, 87)
(0, 9, 88)
(6, 39, 81)
(0, 9, 89)
(0, 9, 90)
(19, 2, 6)
(6, 39, 82)
(12, 71, 0)
(0, 9, 91)
(19, 2, 7)
(6, 39, 83)
(0, 9, 92)
(12, 71, 1)


(0, 11, 39)
(0, 11, 40)
(19, 3, 69)
(6, 41, 25)
(12, 72, 42)
(6, 41, 26)
(19, 3, 70)
(0, 11, 41)
(0, 11, 42)
(19, 3, 71)
(0, 11, 43)
(19, 3, 72)
(6, 41, 27)
(12, 72, 43)
(19, 3, 73)
(0, 11, 44)
(6, 41, 28)
(12, 72, 44)
(6, 41, 29)
(19, 3, 74)
(0, 11, 45)
(0, 11, 46)
(19, 3, 75)
(12, 72, 45)
(19, 3, 76)
(0, 11, 47)
(6, 41, 30)
(19, 3, 77)
(6, 41, 31)
(0, 11, 48)
(12, 72, 46)
(0, 11, 49)
(19, 3, 78)
(0, 11, 50)
(12, 72, 47)
(6, 41, 32)
(6, 41, 33)
(6, 41, 34)
(19, 3, 79)
(12, 72, 48)
(0, 11, 51)
(6, 41, 35)
(19, 3, 80)
(12, 72, 49)
(0, 11, 52)
(19, 3, 81)
(6, 41, 36)
(12, 72, 50)
(0, 11, 53)
(19, 3, 82)
(6, 41, 37)
(12, 72, 51)
(0, 11, 54)
(6, 41, 38)
(12, 72, 52)
(19, 3, 83)
(0, 11, 55)
(19, 3, 84)
(19, 3, 85)
(0, 11, 56)
(19, 3, 86)
(6, 41, 39)
(0, 11, 57)
(12, 72, 53)
(19, 3, 87)
(6, 41, 40)
(19, 3, 88)
(0, 11, 58)
(6, 41, 41)
(12, 72, 54)
(0, 11, 59)
(19, 3, 89)
(12, 72, 55)
(0, 11, 60)
(6, 41, 42)
(19, 3, 90)
(6, 41, 43)
(0, 11, 61)
(12, 72, 56)
(19, 3, 91)
(6, 41, 44)
(0, 11, 62)
(

(6, 42, 80)
(0, 13, 23)
(12, 73, 93)
(0, 13, 24)
(19, 5, 48)
(6, 42, 81)
(12, 73, 94)
(0, 13, 25)
(6, 42, 82)
(0, 13, 26)
(19, 5, 49)
(12, 73, 95)
(6, 42, 83)
(0, 13, 27)
(12, 73, 96)
(19, 5, 50)
(6, 42, 84)
(0, 13, 28)
(12, 73, 97)
(19, 5, 51)
(12, 73, 98)
(0, 13, 29)
(6, 42, 85)
(6, 42, 86)
(0, 13, 30)
(12, 73, 99)
(19, 5, 52)
(12, 73, 100)
(0, 13, 31)
(6, 42, 87)
(19, 5, 53)
(6, 42, 88)
(12, 74, 0)
(0, 13, 32)
(19, 5, 54)
(0, 13, 33)
(12, 74, 1)
(6, 42, 89)
(19, 5, 55)
(12, 74, 2)
(0, 13, 34)
(6, 42, 90)
(12, 74, 3)
(0, 13, 35)
(12, 74, 4)
(19, 5, 56)
(12, 74, 5)
(6, 42, 91)
(19, 5, 57)
(0, 13, 36)
(6, 42, 92)
(19, 5, 58)
(12, 74, 6)
(6, 42, 93)
(0, 13, 37)
(19, 5, 59)
(12, 74, 7)
(0, 13, 38)
(6, 42, 94)
(6, 42, 95)
(12, 74, 8)
(19, 5, 60)
(0, 13, 39)
(12, 74, 9)
(6, 42, 96)
(19, 5, 61)
(0, 13, 40)
(19, 5, 62)
(12, 74, 10)
(19, 5, 63)
(0, 13, 41)
(6, 42, 97)
(12, 74, 11)
(0, 13, 42)
(6, 42, 98)
(0, 13, 43)
(19, 5, 64)
(12, 74, 12)
(6, 42, 99)
(0, 13, 44)
(0, 13, 45)
(6, 42, 100)
(0,

(0, 15, 1)
(12, 75, 70)
(6, 44, 32)
(19, 7, 6)
(12, 75, 71)
(0, 15, 2)
(19, 7, 7)
(12, 75, 72)
(6, 44, 33)
(0, 15, 3)
(19, 7, 8)
(0, 15, 4)
(0, 15, 5)
(6, 44, 34)
(12, 75, 73)
(12, 75, 74)
(6, 44, 35)
(6, 44, 36)
(0, 15, 6)
(19, 7, 9)
(19, 7, 10)
(0, 15, 7)
(12, 75, 75)
(6, 44, 37)
(19, 7, 11)
(12, 75, 76)
(6, 44, 38)
(0, 15, 8)
(19, 7, 12)
(12, 75, 77)
(19, 7, 13)
(6, 44, 39)
(12, 75, 78)
(6, 44, 40)
(0, 15, 9)
(19, 7, 14)
(6, 44, 41)
(0, 15, 10)
(12, 75, 79)
(19, 7, 15)
(0, 15, 11)
(6, 44, 42)
(19, 7, 16)
(0, 15, 12)
(12, 75, 80)
(6, 44, 43)
(0, 15, 13)
(6, 44, 44)
(0, 15, 14)
(12, 75, 81)
(6, 44, 45)
(19, 7, 17)
(0, 15, 15)
(12, 75, 82)
(0, 15, 16)
(0, 15, 17)
(6, 44, 46)
(12, 75, 83)
(19, 7, 18)
(12, 75, 84)
(0, 15, 18)
(6, 44, 47)
(12, 75, 85)
(19, 7, 19)
(0, 15, 19)
(6, 44, 48)
(12, 75, 86)
(19, 7, 20)
(6, 44, 49)
(0, 15, 20)
(6, 44, 50)
(19, 7, 21)
(12, 75, 87)
(6, 44, 51)
(19, 7, 22)
(0, 15, 21)
(12, 75, 88)
(19, 7, 23)
(0, 15, 22)
(12, 75, 89)
(6, 44, 52)
(19, 7, 24)
(12, 75, 

(0, 16, 83)
(12, 77, 38)
(6, 45, 90)
(0, 16, 84)
(12, 77, 39)
(0, 16, 85)
(19, 8, 67)
(12, 77, 40)
(6, 45, 91)
(19, 8, 68)
(12, 77, 41)
(0, 16, 86)
(19, 8, 69)
(6, 45, 92)
(0, 16, 87)
(19, 8, 70)
(12, 77, 42)
(12, 77, 43)
(0, 16, 88)
(12, 77, 44)
(19, 8, 71)
(6, 45, 93)
(12, 77, 45)
(0, 16, 89)
(6, 45, 94)
(12, 77, 46)
(0, 16, 90)
(6, 45, 95)
(12, 77, 47)
(0, 16, 91)
(12, 77, 48)
(19, 8, 72)
(0, 16, 92)
(12, 77, 49)
(19, 8, 73)
(12, 77, 50)
(0, 16, 93)
(19, 8, 74)
(6, 45, 96)
(6, 45, 97)
(12, 77, 51)
(19, 8, 75)
(0, 16, 94)
(19, 8, 76)
(6, 45, 98)
(12, 77, 52)
(19, 8, 77)
(6, 45, 99)
(19, 8, 78)
(12, 77, 53)
(12, 77, 54)
(19, 8, 79)
(6, 45, 100)
(12, 77, 55)
(0, 16, 95)
(19, 8, 80)
(12, 77, 56)
(6, 46, 0)
(19, 8, 81)
(0, 16, 96)
(6, 46, 1)
(12, 77, 57)
(0, 16, 97)
(6, 46, 2)
(19, 8, 82)
(0, 16, 98)
(12, 77, 58)
(19, 8, 83)
(6, 46, 3)
(0, 16, 99)
(19, 8, 84)
(6, 46, 4)
(12, 77, 59)
(0, 16, 100)
(12, 77, 60)
(19, 8, 85)
(19, 8, 86)
(12, 77, 61)
(6, 46, 5)
(0, 17, 0)
(0, 17, 1)
(19, 8, 87

(6, 47, 58)
(19, 10, 28)
(0, 18, 47)
(6, 47, 59)
(0, 18, 48)
(19, 10, 29)
(12, 79, 9)
(0, 18, 49)
(6, 47, 60)
(12, 79, 10)
(19, 10, 30)
(0, 18, 50)
(6, 47, 61)
(12, 79, 11)
(19, 10, 31)
(0, 18, 51)
(6, 47, 62)
(12, 79, 12)
(19, 10, 32)
(12, 79, 13)
(19, 10, 33)
(12, 79, 14)
(6, 47, 63)
(19, 10, 34)
(0, 18, 52)
(6, 47, 64)
(19, 10, 35)
(12, 79, 15)
(0, 18, 53)
(6, 47, 65)
(0, 18, 54)
(19, 10, 36)
(12, 79, 16)
(6, 47, 66)
(0, 18, 55)
(19, 10, 37)
(0, 18, 56)
(12, 79, 17)
(19, 10, 38)
(6, 47, 67)
(12, 79, 18)
(6, 47, 68)
(0, 18, 57)
(19, 10, 39)
(12, 79, 19)
(0, 18, 58)
(19, 10, 40)
(6, 47, 69)
(12, 79, 20)
(19, 10, 41)
(0, 18, 59)
(6, 47, 70)
(12, 79, 21)
(19, 10, 42)
(12, 79, 22)
(0, 18, 60)
(19, 10, 43)
(0, 18, 61)
(6, 47, 71)
(12, 79, 23)
(19, 10, 44)
(0, 18, 62)
(6, 47, 72)
(0, 18, 63)
(12, 79, 24)
(0, 18, 64)
(19, 10, 45)
(0, 18, 65)
(0, 18, 66)
(6, 47, 73)
(19, 10, 46)
(19, 10, 47)
(0, 18, 67)
(19, 10, 48)
(6, 47, 74)
(12, 79, 25)
(19, 10, 49)
(0, 18, 68)
(0, 18, 69)
(19, 10, 50)
(

(6, 49, 23)
(19, 11, 84)
(12, 80, 66)
(0, 20, 25)
(6, 49, 24)
(19, 11, 85)
(0, 20, 26)
(19, 11, 86)
(12, 80, 67)
(6, 49, 25)
(6, 49, 26)
(6, 49, 27)
(12, 80, 68)
(19, 11, 87)
(0, 20, 27)
(0, 20, 28)
(6, 49, 28)
(19, 11, 88)
(12, 80, 69)
(6, 49, 29)
(12, 80, 70)
(19, 11, 89)
(6, 49, 30)
(0, 20, 29)
(12, 80, 71)
(6, 49, 31)
(6, 49, 32)
(19, 11, 90)
(0, 20, 30)
(6, 49, 33)
(12, 80, 72)
(6, 49, 34)
(0, 20, 31)
(19, 11, 91)
(6, 49, 35)
(19, 11, 92)
(6, 49, 36)
(12, 80, 73)
(19, 11, 93)
(19, 11, 94)
(19, 11, 95)
(0, 20, 32)
(12, 80, 74)
(19, 11, 96)
(6, 49, 37)
(0, 20, 33)
(19, 11, 97)
(12, 80, 75)
(19, 11, 98)
(6, 49, 38)
(0, 20, 34)
(12, 80, 76)
(19, 11, 99)
(6, 49, 39)
(19, 11, 100)
(0, 20, 35)
(6, 49, 40)
(19, 12, 0)
(6, 49, 41)
(12, 80, 77)
(0, 20, 36)
(19, 12, 1)
(19, 12, 2)
(12, 80, 78)
(6, 49, 42)
(0, 20, 37)
(19, 12, 3)
(12, 80, 79)
(6, 49, 43)
(19, 12, 4)
(0, 20, 38)
(0, 20, 39)
(0, 20, 40)
(19, 12, 5)
(0, 20, 41)
(0, 20, 42)
(12, 80, 80)
(6, 49, 44)
(19, 12, 6)
(0, 20, 43)
(12, 80

(12, 82, 29)
(6, 50, 76)
(0, 21, 99)
(19, 13, 48)
(12, 82, 30)
(19, 13, 49)
(6, 50, 77)
(0, 21, 100)
(19, 13, 50)
(12, 82, 31)
(6, 50, 78)
(0, 22, 0)
(12, 82, 32)
(19, 13, 51)
(12, 82, 33)
(0, 22, 1)
(6, 50, 79)
(12, 82, 34)
(0, 22, 2)
(6, 50, 80)
(12, 82, 35)
(0, 22, 3)
(19, 13, 52)
(12, 82, 36)
(12, 82, 37)
(19, 13, 53)
(0, 22, 4)
(6, 50, 81)
(12, 82, 38)
(0, 22, 5)
(19, 13, 54)
(6, 50, 82)
(0, 22, 6)
(6, 50, 83)
(12, 82, 39)
(0, 22, 7)
(19, 13, 55)
(6, 50, 84)
(19, 13, 56)
(0, 22, 8)
(0, 22, 9)
(12, 82, 40)
(6, 50, 85)
(19, 13, 57)
(0, 22, 10)
(19, 13, 58)
(12, 82, 41)
(0, 22, 11)
(19, 13, 59)
(6, 50, 86)
(0, 22, 12)
(19, 13, 60)
(12, 82, 42)
(6, 50, 87)
(0, 22, 13)
(12, 82, 43)
(19, 13, 61)
(0, 22, 14)
(0, 22, 15)
(6, 50, 88)
(12, 82, 44)
(12, 82, 45)
(0, 22, 16)
(6, 50, 89)
(19, 13, 62)
(12, 82, 46)
(6, 50, 90)
(0, 22, 17)
(19, 13, 63)
(12, 82, 47)
(0, 22, 18)
(6, 50, 91)
(12, 82, 48)
(0, 22, 19)
(6, 50, 92)
(0, 22, 20)
(6, 50, 93)
(12, 82, 49)
(19, 13, 64)
(6, 50, 94)
(0, 22, 21)

(0, 23, 69)
(12, 83, 95)
(6, 52, 31)
(12, 83, 96)
(0, 23, 70)
(0, 23, 71)
(19, 15, 11)
(6, 52, 32)
(0, 23, 72)
(0, 23, 73)
(6, 52, 33)
(12, 83, 97)
(19, 15, 12)
(12, 83, 98)
(19, 15, 13)
(6, 52, 34)
(0, 23, 74)
(12, 83, 99)
(6, 52, 35)
(19, 15, 14)
(0, 23, 75)
(6, 52, 36)
(12, 83, 100)
(6, 52, 37)
(12, 84, 0)
(0, 23, 76)
(6, 52, 38)
(19, 15, 15)
(0, 23, 77)
(6, 52, 39)
(12, 84, 1)
(19, 15, 16)
(12, 84, 2)
(0, 23, 78)
(12, 84, 3)
(19, 15, 17)
(0, 23, 79)
(6, 52, 40)
(12, 84, 4)
(6, 52, 41)
(0, 23, 80)
(12, 84, 5)
(6, 52, 42)
(12, 84, 6)
(19, 15, 18)
(12, 84, 7)
(0, 23, 81)
(6, 52, 43)
(19, 15, 19)
(0, 23, 82)
(0, 23, 83)
(0, 23, 84)
(6, 52, 44)
(12, 84, 8)
(19, 15, 20)
(6, 52, 45)
(0, 23, 85)
(19, 15, 21)
(12, 84, 9)
(6, 52, 46)
(0, 23, 86)
(19, 15, 22)
(0, 23, 87)
(19, 15, 23)
(6, 52, 47)
(19, 15, 24)
(12, 84, 10)
(0, 23, 88)
(6, 52, 48)
(6, 52, 49)
(0, 23, 89)
(12, 84, 11)
(6, 52, 50)
(19, 15, 25)
(6, 52, 51)
(0, 23, 90)
(12, 84, 12)
(12, 84, 13)
(0, 23, 91)
(12, 84, 14)
(19, 15, 26)


(6, 53, 93)
(12, 85, 49)
(6, 53, 94)
(12, 85, 50)
(19, 16, 65)
(12, 85, 51)
(0, 25, 55)
(12, 85, 52)
(19, 16, 66)
(6, 53, 95)
(0, 25, 56)
(12, 85, 53)
(0, 25, 57)
(19, 16, 67)
(6, 53, 96)
(12, 85, 54)
(0, 25, 58)
(19, 16, 68)
(6, 53, 97)
(0, 25, 59)
(19, 16, 69)
(6, 53, 98)
(0, 25, 60)
(12, 85, 55)
(6, 53, 99)
(19, 16, 70)
(0, 25, 61)
(6, 53, 100)
(12, 85, 56)
(0, 25, 62)
(6, 54, 0)
(0, 25, 63)
(6, 54, 1)
(19, 16, 71)
(12, 85, 57)
(19, 16, 72)
(0, 25, 64)
(12, 85, 58)
(19, 16, 73)
(6, 54, 2)
(0, 25, 65)
(12, 85, 59)
(19, 16, 74)
(0, 25, 66)
(6, 54, 3)
(12, 85, 60)
(6, 54, 4)
(0, 25, 67)
(19, 16, 75)
(12, 85, 61)
(12, 85, 62)
(19, 16, 76)
(0, 25, 68)
(6, 54, 5)
(19, 16, 77)
(0, 25, 69)
(12, 85, 63)
(19, 16, 78)
(6, 54, 6)
(12, 85, 64)
(19, 16, 79)
(0, 25, 70)
(19, 16, 80)
(12, 85, 65)
(6, 54, 7)
(12, 85, 66)
(0, 25, 71)
(19, 16, 81)
(6, 54, 8)
(12, 85, 67)
(19, 16, 82)
(0, 25, 72)
(6, 54, 9)
(19, 16, 83)
(12, 85, 68)
(6, 54, 10)
(0, 25, 73)
(19, 16, 84)
(12, 85, 69)
(0, 25, 74)
(12, 85,

Process ForkPoolWorker-5:
Process ForkPoolWorker-6:
Process ForkPoolWorker-7:
Process ForkPoolWorker-8:
Traceback (most recent call last):
  File "/usr/lib/python3.6/multiprocessing/process.py", line 258, in _bootstrap
    self.run()
  File "/usr/lib/python3.6/multiprocessing/process.py", line 93, in run
    self._target(*self._args, **self._kwargs)
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 119, in worker
    result = (True, func(*args, **kwds))
  File "/usr/lib/python3.6/multiprocessing/pool.py", line 44, in mapstar
    return list(map(*args))
  File "/media/mike_ubuntu/DATA/6_course/ESTAR_operational/prep/cheb.py", line 39, in Process_Point_Cheb
    x_temp, poly_temp = Get_cheb_for_point(matrix, i, idx, grid, max_der_order=n_der, points = points)
  File "/media/mike_ubuntu/DATA/6_course/ESTAR_operational/prep/cheb.py", line 15, in Get_cheb_for_point
    F = matrix.take(I , axis = axis)
KeyboardInterrupt
Traceback (most recent call last):
  File "/usr/lib/python3.6/mul

Загружаем значения в узлах сетки для исходной функции и её производных; из них формируем тензор для дальнейшего использования. Также задаём границы области, по которому будет вычисляться уравнение (в примере - обрезаем начало и конец временного ряда + по 15 элементов с каждой границы, чтобы использовать более "качественные" производные)

In [5]:
u_initial = np.load(path + '/Preprocessing/wave_noised.npy')
derivatives = np.load(path + '/Preprocessing/Derivatives.npy')
variables = np.ones((2 + derivatives.shape[1], ) + u_initial.shape)
variables[1, :] = u_initial
for i_outer in range(0, derivatives.shape[1]):
    variables[i_outer+2] = derivatives[:, i_outer].reshape(variables[i_outer+2].shape) 
    
skipped_elems = 15 
variables = variables[:, skipped_elems:-skipped_elems, skipped_elems:-skipped_elems, skipped_elems:-skipped_elems]

Получаем названия токенов для производных, используя функцию **Define_Derivatives()**. Она получает названия токенов в порядке: 1, u, $\frac{\partial u}{\partial x_1}$, $\frac{\partial^2 u}{\partial x_1^2}$, ... , $\frac{\partial u}{\partial x_2}$, $\frac{\partial^2 u}{\partial x_2^2}$, ...

In [6]:
token_names = Define_Derivatives(u_initial.ndim, max_order = 2)
print(token_names)

('1', 'u', 'du/dx1', 'd^2u/dx1^2', 'du/dx2', 'd^2u/dx2^2', 'du/dx3', 'd^2u/dx3^2')


Задаём объект для обучения уравнения:

In [10]:
Trainer = Equation_Trainer(token_list=token_names, evaluator = derivative_evaluator, 
                           evaluator_params={'token_matrices':variables})

Так как мы не знаем, какой параметр $\alpha$ - коэффициент регуляризации в LASSO, позволяет получить правильную структуру уравнения, мы проводим запуск по сетке из гиперпараметров модели. Сетка в примере строится только по одному параметру ($\alpha$), но в общем виде допустимо задавать сетки сразу по нескольким. Для остальные гиперпараметров модели задаём соответствующие значения. 

In [11]:
Trainer.Parameters_grid(('alpha', 'a_proc', 'r_crossover', 'r_mutation', 'mut_chance', 'pop_size', 'eq_len'), 
                        (20., 100., 3), 0.2, 0.6, 0.5, 1.0, 10, 6)

Запускаем обучение и получаем искомое уравнение в символьной форме

In [ ]:
Trainer.Train(epochs = 200)

in "process cell" function:  <class 'tuple'> ('1', 'u', 'du/dx1', 'd^2u/dx1^2', 'du/dx2', 'd^2u/dx2^2', 'du/dx3', 'd^2u/dx3^2')
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.] [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Population for evolutionary algorithm initialized
Values of main selected parameters:
population size: 10 r_crossover: 0.6 r_mutation: 0.5
Alpha: 20.0
iteration   0
0.006597335135548699 0.005502840862735492 0.0014221576324302508
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
iteration   1
0.006597335135548699 0.005502840862735492 0.0023815449547783026
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
iteration   2
0.006597335135548699 0.005767486575578255 0.0024596939874285276
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
iteration   3
0.006597335135548699 0.005767486575578255 0.0033797304189547776
[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1.]
iteration   4
0.006597335135548699 0.005770437265602844 0.0

In [13]:
import numpy as np
import collections
import os

path = os.path.abspath(os.getcwd())

from prep.derivatives import Preprocess_derivatives

from src.supplementary import Define_Derivatives
from src.term import normalize_ts, Term
from src.trainer import Equation_Trainer

Trainer = Equation_Trainer(token_list=token_names, evaluator = derivative_evaluator, 
                           evaluator_params={'token_matrices':variables})
Trainer.Parameters_grid(('alpha', 'a_proc', 'r_crossover', 'r_mutation', 'mut_chance', 'pop_size', 'eq_len'), 
                        (10., 100., 5), 0.2, 0.6, 0.5, 1.0, 10, 6)
Trainer.Train(epochs = 100)

in "process cell" function:  <class 'tuple'> ('1', 'u', 'du/dx1', 'd^2u/dx1^2', 'du/dx2', 'd^2u/dx2^2', 'du/dx3', 'd^2u/dx3^2')
creating term number 2
creating term number 3
Generationg random term for idx: 3
False [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Generationg random term for idx: 3
False [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Generationg random term for idx: 3
True [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
creating term number 4
Generationg random term for idx: 4
True [1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
creating term number 5
creating term number 2
creating term number 3
creating term number 4
creating term number 5
Generationg random term for idx: 5
True [1. 0. 0. 0. 0. 0. 0. 0. 1. 0. 1. 0. 0. 0. 0. 0.]
creating term number 2
creating term number 3
Generationg random term for idx: 3
False [1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Generationg random term for idx: 3
False [1. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Generati

KeyboardInterrupt: 